version: '3.8'

services:
  web:
    build: .
    container_name: fastapi-project-photoshare
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite+aiosqlite:///./test.db
      SECRET_KEY_JWT: secret_key
      ALGORITHM: HS256
      MAIL_USERNAME: Erozist@meta.ua
      MAIL_PASSWORD: Erozist267
      MAIL_FROM: Erozist@meta.ua
      MAIL_PORT: 465
      MAIL_SERVER: smtp.meta.ua
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CLOUDINARY_NAME: dqcdp5sjs
      CLOUDINARY_API_KEY: 713294667813864
      CLOUDINARY_API_SECRET: q0XeScz_OvMSSKZ9X6e0YrILv_Q
    volumes:
      - .:/app
    
    command: >
      sh -c "alembic revision --autogenerate -m 'Init' && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server

volumes:
  postgres_data:
